# -*- coding: utf-8 -*-
"""liuren.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hkqn-NU1-kXBjZkcvhAyGy3wHWTbub3d
"""

!pip install borax ics

from datetime import date, timedelta
from borax.calendars.lunardate import LunarDate
from ics import Calendar, Event

def generate_liuren_ics(start_date: date, end_date: date, filename: str = "liuren.ics"):
    """
    Generates an iCalendar (.ics) file with Chinese Liu Ren states
    for a given Gregorian date range.
    """

    # Liu Ren mapping based on your provided logic
    liuren_states = {
        1: "大安",
        2: "留連",
        3: "速喜",
        4: "赤口",
        5: "将吉",
        6: "空亡"
    }

    # Initialize the calendar
    c = Calendar()

    # Iterate through every day in the date range
    current_date = start_date
    while current_date <= end_date:
        # 1. Convert Gregorian date to Lunar date
        lunar_date = LunarDate.from_solar_date(
            current_date.year,
            current_date.month,
            current_date.day
        )

        # 2. Extract Lunar month (x) and Lunar day (y)
        x = lunar_date.month
        y = lunar_date.day

        # 3. Calculate z
        z = (x + y - 2) % 6 + 1
        state = liuren_states[z]

        # 4. Create an all-day event for the calendar
        e = Event()
        e.name = f"{state}"
        e.begin = current_date
        e.make_all_day()


        # Add the event to the calendar
        c.events.add(e)

        # Move to the next day
        current_date += timedelta(days=1)

    # 5. Write the calendar data to an .ics file
    with open(filename, 'w', encoding='utf-8') as f:
        f.writelines(c.serialize_iter())

    print(f"Successfully generated '{filename}' from {start_date} to {end_date}.")

# ==========================================
# Example Usage
# ==========================================
if __name__ == "__main__":
    # Define your Gregorian start and end dates here (Year, Month, Day)
    start = date(2026, 1, 1)
    end = date(2030, 12, 31)

    # Run the generator
    generate_liuren_ics(start, end, "liuren-01-2026-12-2030.ics")